# Generated by Django 5.2.13 on 2026-05-13 21:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nlp_engine', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cvdocument',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cvprofile',
            name='cv_document',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='nlp_engine.cvdocument'),
        ),
        migrations.AddField(
            model_name='skillvector',
            name='cv_profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='skill_vector', to='nlp_engine.cvprofile'),
        ),
    ]
