# Generated by Django 5.2.13 on 2026-04-30 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultatMatching',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_total', models.FloatField()),
                ('score_cosinus', models.FloatField()),
                ('score_jaccard', models.FloatField()),
                ('score_experience', models.FloatField()),
                ('score_geo', models.FloatField()),
                ('date_calcul', models.DateTimeField(auto_now_add=True)),
                ('offre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.offre')),
            ],
        ),
    ]
