# Generated by Django 5.2.13 on 2026-04-30 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Offre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('entreprise', models.CharField(blank=True, max_length=255)),
                ('localisation', models.CharField(blank=True, max_length=100)),
                ('competences_requises', models.JSONField(default=list)),
                ('experience_requise', models.IntegerField(default=0)),
                ('type_contrat', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True)),
                ('url_source', models.URLField(max_length=500)),
                ('date_publication', models.DateField(blank=True, null=True)),
                ('date_scraping', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
