# Generated by Django 5.2.13 on 2026-05-13 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('sector', models.CharField(blank=True, max_length=100)),
                ('location', models.CharField(blank=True, max_length=150)),
                ('contract', models.CharField(choices=[('CDI', 'CDI'), ('CDD', 'CDD'), ('Stage', 'Stage'), ('Freelance', 'Freelance'), ('Autre', 'Autre')], default='Autre', max_length=20)),
                ('experience', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True)),
                ('skills', models.JSONField(default=list)),
                ('url', models.URLField(max_length=500, unique=True)),
                ('source', models.CharField(max_length=50)),
                ('published_at', models.DateField(blank=True, null=True)),
                ('scraped_at', models.DateTimeField(auto_now_add=True)),
                ('tfidf_vector', models.JSONField(blank=True, default=dict)),
                ('cluster_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'job_offers',
                'ordering': ['-scraped_at'],
            },
        ),
        migrations.CreateModel(
            name='ScrapingSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('url', models.URLField()),
                ('is_active', models.BooleanField(default=True)),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('nb_offers', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'scraping_sources',
            },
        ),
    ]
