# Generated by Django 5.2.13 on 2026-05-14 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_extra_profile_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='competences',
        ),
        migrations.RemoveField(
            model_name='user',
            name='cv_file',
        ),
        migrations.RemoveField(
            model_name='user',
            name='experience_annees',
        ),
        migrations.RemoveField(
            model_name='user',
            name='localisation',
        ),
    ]
